codecov:
  token: ae885ec3-7e49-40ba-a7b4-342999f4fb21
  require_ci_to_pass: yes

coverage:
  range: 70..100
  round: down
  precision: 2

  status:
    project: yes
    patch: yes
    changes: no

parsers:
  javascript:
    enable_partials: yes
  v1:
    include_full_missed_files: true  # default false
 gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
